#:schema node_modules/wrangler/config-schema.json
name = "next-worker"
main = ".open-next/worker.js"

compatibility_date = "2024-12-20"
compatibility_flags = ["nodejs_compat"]

# Assets used for files and cache priming.
assets = { directory = ".open-next/assets", binding = "ASSETS" }

[placement]
mode = "smart"

[[d1_databases]]
binding = "DATABASE"
database_name = "cloudflare-workers-nextjs-saas"
database_id = "0d36e6e4-58a7-4c30-a090-f116d6bc4a3d"
migrations_dir = "src/db/migrations"

[[kv_namespaces]]
binding = "NEXT_CACHE_WORKERS_KV"
id = "f5c002f17bc9406bb24a9adc9f451fd9"
